package com.tarazgroup.tws.dao.sale;

import com.tarazgroup.tws.dao.TCrudRepository;
import com.tarazgroup.tws.model.sale.SaleReportVoucher;
import com.tarazgroup.tws.util.global.TParameter;
import com.tarazgroup.tws.util.global.responseheader.Col;
import com.tarazgroup.tws.util.global.responseheader.Meta;
import com.tarazgroup.tws.util.global.responseheader.Type;
import org.springframework.data.repository.CrudRepository;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

/**
 * @author A.Salehi
 */
public interface SaleReportVoucherRepository extends TCrudRepository<SaleReportVoucher>, CrudRepository<SaleReportVoucher, BigDecimal> {

    default List<SaleReportVoucher> saleShowReportVoucher(SaleReportVoucher saleReportVoucher) {
        List<TParameter<?>> tParameters = new ArrayList<>();
        tParameters.add(new TParameter<>("Filter", null));
        tParameters.add(new TParameter<>("OtherFilter", null));
        tParameters.add(new TParameter<>("ServerFilter", saleReportVoucher._serverFilter()));
        tParameters.add(new TParameter<>("YearFilter", saleReportVoucher._yearFilter()));
        tParameters.add(new TParameter<>("UserAccessFilter", null));
        tParameters.add(new TParameter<>("GeneralFilter", null));
        tParameters.add(new TParameter<>("IsXFieldsHeader", null));
        tParameters.add(new TParameter<>("IsXFieldsDetail", null));
        tParameters.add(new TParameter<>("PageFilter", saleReportVoucher._pageFilter()));
        return showSP("SaleReport_Voucher", tParameters, true);
    }

    default Meta meta() {
        ArrayList<Col> cols = new ArrayList<>();
        cols.add(new Col(null, "voucherHeaderID", "voucherHeaderID", Type.DECIMAL, 0, false, false, true));
        cols.add(new Col(null, "voucherDetailID", "VoucherDetailID", Type.DECIMAL, 100, false, false, false));
        cols.add(new Col(null, "voucherNumber", "سند|شماره", Type.STRING, 130, true, true, false));
        cols.add(new Col(null, "voucherDate", "سند|تاریخ", Type.STRING, 100, true, true, false));
        cols.add(new Col(null, "yearID", "نام لاتین بانک", Type.STRING, 120, true, true, false));
        cols.add(new Col(null, "voucherDateG", "سند|تاریخ میلادی", Type.STRING, 100, true, true, false));
        cols.add(new Col(null, "customerCode", "مشتری|کد", Type.STRING, 100, true, true, false));
        cols.add(new Col(null, "customerName", "مشتری|عنوان", Type.STRING, 120, true, true, false));
        cols.add(new Col(null, "storeCode", "کد انبار", Type.STRING, 100, true, true, false));
        cols.add(new Col(null, "storeName", "نام انبار", Type.STRING, 100, true, true, false));
        cols.add(new Col(null, "saleCenterDesc", "مرکز فروش", Type.STRING, 100, true, true, false));
        cols.add(new Col(null, "deliverCenterDesc", "محل تحویل", Type.STRING, 100, true, true, false));
        cols.add(new Col(null, "voucherDesc", "توضيحات فاکتور", Type.STRING, 100, true, true, false));
        cols.add(new Col(null, "voucherTypeID", "voucherTypeID", Type.DECIMAL, 100, false, false, false));
        cols.add(new Col(null, "referNumber", "شماره عطف", Type.STRING, 100, true, true, false));
        cols.add(new Col(null, "referDate", "تاریخ عطف", Type.STRING, 100, true, true, false));
        cols.add(new Col(null, "salesManName", "نام فروشنده", Type.STRING, 100, true, true, false));
        cols.add(new Col(null, "marketingManName", "نام بازاریاب", Type.STRING, 100, true, true, false));
        cols.add(new Col(null, "salesManCode", "کد فروشنده", Type.STRING, 100, true, true, false));
        cols.add(new Col(null, "marketingManCode", "کد بازاریاب", Type.STRING, 100, true, true, false));
        cols.add(new Col(null, "voucherTypeDesc", "VoucherTypeDesc", Type.STRING, 100, false, false, false));
        cols.add(new Col(null, "refTypeID", "refTypeID", Type.DECIMAL, 100, false, false, false));
        cols.add(new Col(null, "refTypeDesc", "نوع مرجع", Type.STRING, 100, true, true, false));
        cols.add(new Col(null, "tafsiliDesc", "tafsiliDesc", Type.STRING, 100, false, false, false));
        cols.add(new Col(null, "tafsiliCode", "مشتری|کد تفصیلی", Type.STRING, 100, true, true, false));
        cols.add(new Col(null, "saleTypeDesc", "نوع فروش", Type.STRING, 100, true, true, false));
        cols.add(new Col(null, "currencyName", "نوع ارز", Type.STRING, 100, true, true, false));
        cols.add(new Col(null, "voucherStatDesc", "وضعیت سند", Type.STRING, 100, true, true, false));
        cols.add(new Col(null, "extraDesc", "توضیحات", Type.STRING, 100, true, true, false));
        cols.add(new Col(null, "refTypeDesc", "refTypeDesc", Type.DECIMAL, 100, false, false, false));
        cols.add(new Col(null, "creatorName", "تنظیم کننده", Type.STRING, 100, true, true, false));
        cols.add(new Col(null, "paymentwayDesc", "شرایط پرداخت", Type.STRING, 100, true, true, false));
        cols.add(new Col(null, "customVTypeDesc", "نوع سند", Type.STRING, 100, true, true, false));
        cols.add(new Col(null, "serverDesc", "محل صدور", Type.STRING, 100, true, true, false));
        cols.add(new Col(null, "invNumber", "شماره حواله", Type.DECIMAL, 100, true, true, false));
        cols.add(new Col(null, "secondNumber", "شماره فرعی", Type.STRING, 100, true, true, false));
        cols.add(new Col(null, "accNumber", "سند حسابداری|شماره", Type.DECIMAL, 100, true, true, false));
        cols.add(new Col(null, "accDate", "سند حسابداری|تاریخ", Type.STRING, 100, true, true, false));
        cols.add(new Col(null, "center1Code", "سطح 5|کد", Type.STRING, 100, true, true, false));
        cols.add(new Col(null, "center2Code", "سطح 6|کد", Type.DECIMAL, 100, false, false, false));
        cols.add(new Col(null, "center3Code", "سطح 7|کد", Type.DECIMAL, 100, false, false, false));
        cols.add(new Col(null, "center1Desc", "سطح 5|شرح", Type.STRING, 100, true, true, false));
        cols.add(new Col(null, "center2Desc", "سطح 6|شرح", Type.STRING, 100, true, true, false));
        cols.add(new Col(null, "center3Desc", "سطح 7|شرح", Type.STRING, 100, true, true, false));
        cols.add(new Col(null, "isPromotion", "isPromotion", Type.BOOLEAN, 100, false, false, false));
        cols.add(new Col(null, "quantity", "مقدار", Type.DECIMAL, 100, true, true, false));
        cols.add(new Col(null, "fee", "فی", Type.DECIMAL, 100, true, true, false));
        cols.add(new Col(null, "bonusQ", "جايزه", Type.DECIMAL, 100, true, true, false));
        cols.add(new Col(null, "detailXDesc", "شرح", Type.STRING, 100, true, true, false));
        cols.add(new Col(null, "rowPriceOLD", "rowPriceOLD", Type.DECIMAL, 100, false, false, false));
        cols.add(new Col(null, "computeValue", "تعداد واحد فرعی", Type.DECIMAL, 100, true, true, false));
        cols.add(new Col(null, "goodsCode", "کالا|کد", Type.STRING, 100, true, true, false));
        cols.add(new Col(null, "barCode", "کالا|بارکد", Type.STRING, 100, true, true, false));
        cols.add(new Col(null, "techInfo", "کالا|مشخصات فنی", Type.STRING, 100, true, true, false));
        cols.add(new Col(null, "latinDesc", "کالا|شرح لاتین", Type.STRING, 100, true, true, false));
        cols.add(new Col(null, "groupCode", "گروه فرعی کالا|کد", Type.STRING, 100, true, true, false));
        cols.add(new Col(null, "goodsDesc", "کالا|شرح", Type.STRING, 100, true, true, false));
        cols.add(new Col(null, "groupDesc", "گروه فرعی کالا|شرح", Type.STRING, 100, true, true, false));
        cols.add(new Col(null, "unitName", "واحد کالا", Type.STRING, 100, true, true, false));
        cols.add(new Col(null, "referNum", "referNum", Type.DECIMAL, 100, false, false, false));
        cols.add(new Col(null, "referD", "referD", Type.STRING, 100, false, false, false));
        cols.add(new Col(null, "dReferNumber", "شماره مرجع", Type.DECIMAL, 100, true, true, false));
        cols.add(new Col(null, "dReferDate", "تاریخ مرجع", Type.STRING, 100, true, true, false));
        cols.add(new Col(null, "serialType", "serialType", Type.INTEGER, 100, false, false, false));
        cols.add(new Col(null, "serialDesc", "serialDesc", Type.STRING, 100, false, false, false));
        cols.add(new Col(null, "differentialDesc", "مشتقات کالا", Type.STRING, 100, true, true, false));
        cols.add(new Col(null, "percomAddress", "مشتری|آدرس", Type.STRING, 100, true, true, false));
        cols.add(new Col(null, "customField1", "وزن", Type.STRING, 100, true, true, false));
        cols.add(new Col(null, "customField2", "customField2", Type.STRING, 100, true, true, false));
        cols.add(new Col(null, "customField3", "customField3", Type.STRING, 100, false, false, false));
        cols.add(new Col(null, "customField4", "customField4", Type.STRING, 100, false, false, false));
        cols.add(new Col(null, "customField5", "customField5", Type.STRING, 100, false, false, false));
        cols.add(new Col(null, "customField6", "customField6", Type.STRING, 100, false, false, false));
        cols.add(new Col(null, "customField7", "customField7", Type.STRING, 100, false, false, false));
        cols.add(new Col(null, "customField8", "customField8", Type.STRING, 100, false, false, false));
        cols.add(new Col(null, "customField9", "customField9", Type.STRING, 100, false, false, false));
        cols.add(new Col(null, "customField10", "customField10", Type.STRING, 100, false, false, false));
        cols.add(new Col(null, "customField11", "customField11", Type.DECIMAL, 100, false, false, false));
        cols.add(new Col(null, "customField12", "customField12", Type.STRING, 100, false, false, false));
        cols.add(new Col(null, "customField13", "customField13", Type.STRING, 100, false, false, false));
        cols.add(new Col(null, "customField14", "customField14", Type.STRING, 100, false, false, false));
        cols.add(new Col(null, "customField15", "customField15", Type.STRING, 100, false, false, false));
        cols.add(new Col(null, "customField16", "customField16", Type.STRING, 100, false, false, false));
        cols.add(new Col(null, "customField17", "customField17", Type.STRING, 100, false, false, false));
        cols.add(new Col(null, "customField18", "customField18", Type.STRING, 100, false, false, false));
        cols.add(new Col(null, "customField19", "customField19", Type.STRING, 100, false, false, false));
        cols.add(new Col(null, "customField20", "customField20", Type.STRING, 100, false, false, false));
        cols.add(new Col(null, "customField21", "customField21", Type.STRING, 100, false, false, false));
        cols.add(new Col(null, "customField22", "customField22", Type.STRING, 100, false, false, false));
        cols.add(new Col(null, "customField23", "customField23", Type.STRING, 100, false, false, false));
        cols.add(new Col(null, "customField24", "customField24", Type.STRING, 100, false, false, false));
        cols.add(new Col(null, "customField24", "customField25", Type.STRING, 100, false, false, false));
        cols.add(new Col(null, "feeAgreement", "فی برآوردی", Type.DECIMAL, 100, false, false, false));
        cols.add(new Col(null, "feeDiscountPrice", "تخفیف نقدی", Type.DECIMAL, 100, false, false, false));
        cols.add(new Col(null, "feeDiscountPercent", "تخفیف درصدی", Type.DECIMAL, 100, false, false, false));
        cols.add(new Col(null, "feeFrieghtCharges", "مبلغ کرایه حمل", Type.DECIMAL, 100, false, false, false));
        cols.add(new Col(null, "lCNo", "اعتبار|شماره گشایش", Type.STRING, 100, false, false, false));
        cols.add(new Col(null, "lCOpenDate", "اعتبار|تاریخ گشایش", Type.STRING, 100, false, false, false));
        cols.add(new Col(null, "greenLicNo", "اعتبار|شماره پروانه سبز", Type.STRING, 100, false, false, false));
        cols.add(new Col(null, "kootajNo", "اعتبار|شماره کوتاژ", Type.STRING, 100, false, false, false));
        cols.add(new Col(null, "greenLicDate", "اعتبار|تاریخ صدور پروانه سبز", Type.STRING, 100, false, false, false));
        cols.add(new Col(null, "lCDisChargCode", "گمرک مقصد|کد", Type.STRING, 100, true, true, false));
        cols.add(new Col(null, "lCDisChargDesc", "گمرک مقصد|شرح", Type.STRING, 100, true, true, false));
        cols.add(new Col(null, "agrNo", "قرارداد|شماره سند", Type.DECIMAL, 100, false, false, false));
        cols.add(new Col(null, "agrIndicatorNo", "قرارداد|شماره اندیکاتور", Type.STRING, 100, true, false, false));
        cols.add(new Col(null, "agrReferID", "agrReferID", Type.DECIMAL, 100, false, false, false));
        cols.add(new Col(null, "customField1Header", "وزن", Type.STRING, 100, false, false, false));
        cols.add(new Col(null, "customField2Header", "وزن", Type.STRING, 100, false, false, false));
        cols.add(new Col(null, "customField3Header", "وزن", Type.STRING, 100, false, false, false));
        cols.add(new Col(null, "customField4Header", "وزن", Type.STRING, 100, false, false, false));
        cols.add(new Col(null, "customField5Header", "وزن", Type.STRING, 100, false, false, false));
        cols.add(new Col(null, "customField6Header", "وزن", Type.STRING, 100, false, false, false));
        cols.add(new Col(null, "customField7Header", "وزن", Type.STRING, 100, false, false, false));
        cols.add(new Col(null, "customField8Header", "وزن", Type.STRING, 100, false, false, false));
        cols.add(new Col(null, "customField9Header", "وزن", Type.STRING, 100, false, false, false));
        cols.add(new Col(null, "customField10Header", "وزن", Type.STRING, 100, false, false, false));
        cols.add(new Col(null, "customField11Header", "customField11Header", Type.STRING, 100, false, false, false));
        cols.add(new Col(null, "customField12Header", "customField12Header", Type.STRING, 100, false, false, false));
        cols.add(new Col(null, "customField13Header", "customField13Header", Type.STRING, 100, false, false, false));
        cols.add(new Col(null, "customField14Header", "customField14Header", Type.STRING, 100, false, false, false));
        cols.add(new Col(null, "customField15Header", "customField15Header", Type.STRING, 100, false, false, false));
        cols.add(new Col(null, "customField16Header", "customField16Header", Type.STRING, 100, false, false, false));
        cols.add(new Col(null, "customField17Header", "customField17Header", Type.STRING, 100, false, false, false));
        cols.add(new Col(null, "customField18Header", "customField18Header", Type.DECIMAL, 100, false, false, false));
        cols.add(new Col(null, "customField19Header", "customField19Header", Type.STRING, 100, false, false, false));
        cols.add(new Col(null, "customField20Header", "customField20Header", Type.STRING, 100, false, false, false));
        cols.add(new Col(null, "customField21Header", "customField21Header", Type.STRING, 100, false, false, false));
        cols.add(new Col(null, "customField22Header", "customField22Header", Type.STRING, 100, false, false, false));
        cols.add(new Col(null, "customField23Header", "customField23Header", Type.STRING, 100, false, false, false));
        cols.add(new Col(null, "customField24Header", "customField24Header", Type.STRING, 100, false, false, false));
        cols.add(new Col(null, "customField25Header", "customField25Header", Type.STRING, 100, false, false, false));
        cols.add(new Col(null, "isBasket", "سبد کالا", Type.BOOLEAN, 100, true, true, false));
        cols.add(new Col(null, "cancelQuantity", "ابطال|مقدار ابطال شده - واحد اصلی", Type.DECIMAL, 100, true, true, false));
        cols.add(new Col(null, "secCancelQuantity", "secCancelQuantity", Type.DECIMAL, 100, false, false, false));
        cols.add(new Col(null, "usedQ", "usedQ", Type.DECIMAL, 100, false, false, false));
        cols.add(new Col(null, "cancelRemain", "cancelRemain", Type.DECIMAL, 100, false, false, false));
        cols.add(new Col(null, "remainQ", "مانده از مرجع", Type.DECIMAL, 100, true, true, false));
        cols.add(new Col(null, "quantity2", "مقدار فرعی", Type.DECIMAL, 100, false, false, false));
        cols.add(new Col(null, "isCancel", "ابطال|ابطال شده کلی", Type.BOOLEAN, 100, true, true, false));
        cols.add(new Col(null, "isQuantityCancel", "ابطال|ابطال شده مقداری", Type.BOOLEAN, 100, true, true, false));
        cols.add(new Col(null, "invRefDesc", "وضعیت حواله فروش", Type.STRING, 100, true, true, false));
        cols.add(new Col(null, "invRefID", "invRefID", Type.DECIMAL, 100, false, false, false));
        cols.add(new Col(null, "invFee", "invFee", Type.DECIMAL, 100, false, false, false));
        cols.add(new Col(null, "contractNumber", "اطلاعات تکمیلی|شماره قرارداد", Type.STRING, 100, true, true, false));
        cols.add(new Col(null, "contractDate", "اطلاعات تکمیلی|تاریخ قرارداد", Type.STRING, 100, true, true, false));
        cols.add(new Col(null, "bruntNumber", "اطلاعات تکمیلی|شماره بارنامه", Type.STRING, 100, true, true, false));
        cols.add(new Col(null, "carNumber", "اطلاعات تکمیلی|شماره ماشین", Type.STRING, 100, true, true, false));
        cols.add(new Col(null, "otherDesc", "اطلاعات تکمیلی|توضیحات", Type.STRING, 100, true, true, false));
        cols.add(new Col(null, "xDesc", "اطلاعات تکمیلی|سایر توضیحات", Type.STRING, 100, true, true, false));
        cols.add(new Col(null, "dayCount", "تسویه|تعداد روز", Type.DECIMAL, 100, true, true, false));
        cols.add(new Col(null, "settleDate", "تسویه|تاریخ", Type.STRING, 100, true, true, false));
        cols.add(new Col(null, "baseGroupCode", "گروه اصلی کالا|کد", Type.STRING, 100, true, true, false));
        cols.add(new Col(null, "baseGroupDesc", "گروه اصلی گروه اصلی کالا|شرح", Type.STRING, 100, true, true, false));
        cols.add(new Col(null, "driverName", "اطلاعات تکمیلی|نام راننده", Type.STRING, 100, true, true, false));
        cols.add(new Col(null, "distName", "اطلاعات تکمیلی|نام مامور پخش", Type.STRING, 100, true, true, false));
        cols.add(new Col(null, "geoCode", "منطقه جغرافیایی|کد", Type.STRING, 100, true, true, false));
        cols.add(new Col(null, "geoDesc", "منطقه جغرافیایی|شرح", Type.STRING, 100, true, true, false));
        cols.add(new Col(null, "percomTel", "مشتری|تلفن", Type.STRING, 100, true, true, false));
        cols.add(new Col(null, "percomMobile", "مشتری|موبایل", Type.STRING, 100, true, true, false));
        cols.add(new Col(null, "nationalCode", "مشتری|کد ملی", Type.DECIMAL, 100, false, false, false));
        cols.add(new Col(null, "economicCode", "مشتری|کد اقتصادی", Type.STRING, 100, true, true, false));
        cols.add(new Col(null, "stateCode", "استان|کد", Type.STRING, 100, true, true, false));
        cols.add(new Col(null, "stateDesc", "استان|شرح", Type.STRING, 100, true, true, false));
        cols.add(new Col(null, "cityCode", "شهر|کد", Type.STRING, 100, true, true, false));
        cols.add(new Col(null, "cityDesc", "شهر|شرح", Type.STRING, 100, true, true, false));
        cols.add(new Col(null, "rRowMabPrice", "تخفیف ردیفی|مبلغی", Type.DECIMAL, 100, true, true, false));
        cols.add(new Col(null, "rRowMabPercent", "تخفیف ردیفی|درصدی", Type.DECIMAL, 100, true, true, false));
        cols.add(new Col(null, "manNo", "مدیریت توزیع|شماره سند", Type.DECIMAL, 100, true, true, false));
        cols.add(new Col(null, "manDate", "مدیریت توزیع|تاریخ", Type.STRING, 100, true, true, false));
        cols.add(new Col(null, "manDriverName", "مدیریت توزیع|نام راننده", Type.STRING, 100, false, false, false));
        cols.add(new Col(null, "manDistName", "مدیریت توزیع|مامور پخش", Type.STRING, 100, true, true, false));
        cols.add(new Col(null, "manSaleMan", "مدیریت توزیع|نام فروشنده", Type.STRING, 100, true, true, false));
        cols.add(new Col(null, "currencyID", "creatorID", Type.DECIMAL, 100, false, false, false));
        cols.add(new Col(null, "vDID", "creatorID", Type.DECIMAL, 100, false, false, false));
        cols.add(new Col(null, "eLX10000007", "عوامل اضافات و کسور|مالیات بر ارزش افزوده (دستی)", Type.DECIMAL, 100, true, true, false));
        cols.add(new Col(null, "eLX10000008", "creatorID", Type.DECIMAL, 100, false, false, false));
        cols.add(new Col(null, "eLX10000012", "creatorID", Type.DECIMAL, 100, false, false, false));
        cols.add(new Col(null, "eLX10000013", "creatorID", Type.DECIMAL, 100, false, false, false));
        cols.add(new Col(null, "eLX10000014", "creatorID", Type.DECIMAL, 100, false, false, false));
        cols.add(new Col(null, "eLX10000015", "creatorID", Type.DECIMAL, 100, false, false, false));
        cols.add(new Col(null, "eLX10000016", "creatorID", Type.DECIMAL, 100, false, false, false));
        cols.add(new Col(null, "eLX10000017", "creatorID", Type.DECIMAL, 100, false, false, false));
        cols.add(new Col(null, "eLX10000018", "creatorID", Type.DECIMAL, 100, false, false, false));
        cols.add(new Col(null, "eLX10000020", "creatorID", Type.DECIMAL, 100, false, false, false));
        cols.add(new Col(null, "eLX10000003", "creatorID", Type.DECIMAL, 100, false, false, false));
        cols.add(new Col(null, "eLX10000005", "creatorID", Type.DECIMAL, 100, false, false, false));
        cols.add(new Col(null, "grossRowPrice", "مبلغ ناخالص", Type.DECIMAL, 100, true, true, false));
        cols.add(new Col(null, "totalFeeFrieghtCharges", "TotalFeeFrieghtCharges", Type.DECIMAL, 100, false, false, false));
        cols.add(new Col(null, "rowPrice", "مبلغ خالص", Type.DECIMAL, 100, true, true, false));

        return new Meta(cols);
    }

}
